Repository Dannkol/zoologico_campus, pull requests merged in 2023-08, with the labels that each got.

#1 [ZCT-8] Pull request Investigacion
  README.md
Labels: documentation

#2 [ ZCT-12 ] Creacion de colecciones y Schemas json para la base de datos
  README.md
  database/zooSchemas.mongodb
  docs/database/readme.md
  docs/img/Alta_personal.png
  docs/img/Baja_personal.png
Labels: enhancement

#3 [ ZCT-3 ] GitHub PR Title docs: :memo: Documentación de la base de datos
  docs/database/readme.md
Labels: documentation

#4 [ ZCT-17 ] feat: ⚡️Estructura backend
  .env-explame
  .gitignore
  package.json
  src/config/connection.js
  src/controllers/AnimalController.js
  src/middleware/middleware_example.js
  src/models/Animal.js
  src/routes/v1/animal.routes.js
Labels: enhancement, help wanted, good first issue, question

#5 [ ZCT-20 ] Gestion de Habitats
  .env-explame
  .gitignore
  README.md
  app.js
  database/zooSchemas.mongodb
  docs/database/readme.md
  docs/img/Alta_personal.png
  docs/img/Baja_personal.png
  docs/img/Flujograma-Adquisición.png
  docs/img/Flujograma-AdquisiciónPorDecomiso.png
  docs/img/Flujograma-Donacion.png
  docs/img/Flujograma-Fuga.png
  docs/img/Flujograma-Intercambio.png
  docs/img/Flujograma-Robo.png
  docs/img/Flujograma-defuncion.png
  package.json
  prueba.js
  src/config/configExpress.js
  src/config/connection.js
  src/controllers/AnimalController.js
  src/controllers/HabitatController.js
  src/controllers/PersonalController.js
  src/middleware/middleware_example.js
  src/middleware/middleware_validate_habitat.js
  src/middleware/middleware_validate_personal.js
  src/middleware/middlware_baja_personal.js
  src/models/Animal.js
  src/models/Habitat.js
  src/models/Personal.js
  src/routes/v1/animal.routes.js
  src/routes/v1/documentacionEndpoints.txt
  src/routes/v1/habitat.routes.js
  src/routes/v1/personal.routes.js
Labels: enhancement

#6 [ ZCT-7 ] Creacion de los endpoint Administración de Animal
  app.js
  database/zooSchemas.mongodb
  package.json
  src/controllers/AnimalController.js
  src/middleware/middleware_Validate_Animal.js
  src/middleware/middleware_validate_baja.js
  src/middleware/middleware_validate_bonacion.js
  src/middleware/middleware_validate_fuga.js
  src/models/Animal.js
  src/routes/readme.md
  src/routes/v1/animal.routes.js
Labels: documentation, enhancement

#7 [ ZCT-19 ] Creacion de los endpoints Gestión de Visitantes
  app.js
  database/zooSchemas.mongodb
  docs/database/readme.md
  src/controllers/VisitantesController.js
  src/middleware/middleware_validate_fuga.js
  src/middleware/middleware_validate_visita.js
  src/models/visitas.js
  src/routes/readme.md
  src/routes/v1/visitas.routes.js
Labels: documentation, enhancement, Database
